[project]
name = "advent-of-code"
version = "0.1.0"
description = "My Advent of Code solutions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "ruff>=0.14.8",
]
